### PR TITLE
update json parser gem ojh

### PR DESCRIPTION
**Pull request by jbowles**

### CODE REVIEW

**Comment by hopsoft** [comment]
Why did you close the pull?

**Comment by jbowles** [comment]
haha, i didn't mean to do the PR against this branch but against the PF fork of it :)

and I noticed you moved off `Oj` to `JSON`... was this to move off the C-based parser?

**Comment by hopsoft** [comment]
Just trying to reduce the number of required 3rd party dependencies.

**Comment by jbowles** [comment]
whew that was close, i was afraid you were gonna say it was so you could use in a jruby app :)

[which i did once, by the way.. as a test to see how mystique would run in jruby. glad i never had to do that!]

**Pull request closed without merging**
